#!/usr/bin/env python3

import rospy
from onrobot_mg_control.msg import OnRobotMGInput


def printStatus(status):
    """ Prints the status string generated by the statusInterpreter. """

    rospy.loginfo(statusInterpreter(status))


def OnRobotMGStatusListener():
    """ Initializes the node and subscribe to the OnRobotMGInput topic. """

    rospy.init_node(
        'OnRobotMGStatusListener', anonymous=True, log_level=rospy.DEBUG)
    rospy.Subscriber("OnRobotMGInput", OnRobotMGInput, printStatus)
    rospy.spin()


def statusInterpreter(status):
    """ Generates a string according to the current status. """

    output = '\n-----\nOnRobot MG status interpreter\n-----\n'

    # gGDT
    output += 'gGDT = ' + str(status.gGDT) + ': '
    output += 'Grip detected: ' + str(status.gGDT) + '\n'

    # gWDT
    output += 'gWDT = ' + str(status.gWDT) + ': '
    output += 'Work detected: ' + str(status.gWDT) + '\n'

    # gWDR
    output += 'gWDR = ' + str(status.gWDR) + ': '
    output += 'Work dropped: ' + str(status.gWDR) + '\n'

    # gSGF
    output += 'gSGF = ' + str(status.gSGF) + ': '
    output += 'Smart grip failed: ' + str(status.gSGF) + '\n'

    # gMGS
    output += 'gMGS = ' + str(status.gMGS) + ': '
    output += 'Current magnet strength: ' + str(status.gMGS) + '\n'

    return output


if __name__ == '__main__':
    OnRobotMGStatusListener()
